include: package:lint/strict.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    sort_constructors_first: true

analyzer:
  errors:
    avoid_print: error
    prefer_single_quotes: error
    sort_constructors_first: error
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "test/**"
    - "build/**"
