name: five_on_4_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  go_router: ^6.0.1
  isar: ^3.0.5
  isar_generator: ^3.0.5
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_flutter_libs: ^3.0.5
  json_serializable: ^6.5.4
  lint: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
